# Generated by Django 4.0.4 on 2023-05-15 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv_pdf_view', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinfo',
            name='email',
            field=models.CharField(default='catarina.em12@gmail.com', max_length=500),
            preserve_default=False,
        ),
    ]
