# Generated by Django 4.0.4 on 2023-05-15 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv_pdf_view', '0002_personalinfo_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalinfo',
            name='linkedin',
        ),
    ]
