from django.urls import path
from .views import *

urlpatterns = [
    path('personal_info/pdf/<int:pk>/', PersonalInfoPdfView.as_view(),
         name='personal_info_as_pdf'),
    path('personal_info/update/<int:pk>/', PersonalInfoUpdateView.as_view(),
         name='personal_info_update'),
    path('personal_info', PersonalInfoView.as_view(), name='personal_info'),
    path('job', JobView.as_view(), name='job'),
    path('study', StudyView.as_view(), name='study'),
    path('social_media', SocialMediaView.as_view(), name='social_media'),
    path('language', LanguageView.as_view(), name='language'),
    path('soft_skill', SoftSkillView.as_view(), name='soft_skill'),
    path('hard_skill', HardSkillView.as_view(), name='hard_skill'),
    path('company/pdf/<int:pk>/', CompanyPdfView.as_view(),
         name='company_as_pdf'),
    path('company/update/<int:pk>/', CompanyUpdateView.as_view(),
         name='company_update'),
    path('company/create/',
         CompanyCreateView.as_view(), name='company_create'),
    path('company', CompanyView.as_view(), name='company'),
    path('cover_letter/pdf/<int:pk>/', CoverLetterPdfView.as_view(),
         name='cover_letter_as_pdf'),
    path('cover_letter/update/<int:pk>/', CoverLetterUpdateView.as_view(),
         name='cover_letter_update'),
    path('cover_letter/create/',
         CoverLetterCreateView.as_view(), name='cover_letter_create'),
    path('cover_letter', CoverLetterView.as_view(), name='cover_letter'),
]
